#! /bin/bash
# Note the shebang above is only for proper syntax highlighting of this file.
# There is absolutely no sense in launching the file, it is intended to 
# sourcing by some other bash file.
#

# Colour constants
declare -r \
        ansi_black='\033[30m' \
        ansi_black_bold='\033[0;30;1m' \
        ansi_red='\033[31m' \
        ansi_red_bold='\033[0;31;1m' \
        ansi_green='\033[32m' \
        ansi_green_bold='\033[0;32;1m' \
        ansi_yellow='\033[33m' \
        ansi_yellow_bold='\033[0;33;1m' \
        ansi_blue='\033[34m' \
        ansi_blue_bold='\033[0;34;1m' \
        ansi_magenta='\033[35m' \
        ansi_magenta_bold='\033[0;35;1m' \
        ansi_cyan='\033[36m' \
        ansi_cyan_bold='\033[0;36;1m' \
        ansi_white='\033[37m' \
        ansi_white_bold='\033[0;37;1m' \
        ansi_reset='\033[0m'

declare -r ansi_grey="$ansi_black_bold"

declare -rA ANSI_COLOR=(
    [black]="$ansi_black"
    [black_bold]="$ansi_black_bold"
    [grey]="$ansi_grey"
    [red]="$ansi_red"
    [red_bold]="$ansi_red_bold"
    [green]="$ansi_green"
    [green_bold]="$ansi_green_bold"
    [yellow]="$ansi_yellow"
    [yellow_bold]="$ansi_yellow_bold"
    [blue]="$ansi_blue"
    [blue_bold]="$ansi_blue_bold"
    [magenta]="$ansi_magenta"
    [magenta_bold]="$ansi_magenta_bold"
    [cyan]="$ansi_cyan"
    [cyan_bold]="$ansi_cyan_bold"
    [white]="$ansi_white"
    [white_bold]="$ansi_white_bold"
    [reset]="$ansi_reset"
)

# Colour-echo.
# Argument $1 = color (defaults to nothing if not specified)
# Other arguments will be directly forwarded to echo
#
# cecho grey hello
# cecho $ansi_grey hello
# cecho red_bold -e 'hello\nworld'
#
function cecho {
    local color=${ANSI_COLOR[$1]}
    [ -n "$color" ] || { [[ "$1" == \\033\[* ]] && color="$1" ; } && shift ;
    local opt=
    [ "$1" == "-n" ] && { opt=$1 ; shift ; }

    # Print colour escape sequences only for TTY stdout
    [ -t 1 ] && echo -ne "$color" ; echo -n "$@" ; [ -t 1 ] && echo -e $opt "$ansi_reset"
}
